using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TraliVali.Api.Models;
using TraliVali.Auth;

namespace TraliVali.Api.Controllers;

/// <summary>
/// Controller for invite management operations
/// </summary>
[ApiController]
[Route("invites")]
[Authorize]
public class InvitesController : ControllerBase
{
    private readonly IInviteService _inviteService;
    private readonly ILogger<InvitesController> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="InvitesController"/> class
    /// </summary>
    public InvitesController(
        IInviteService inviteService,
        ILogger<InvitesController> logger)
    {
        _inviteService = inviteService ?? throw new ArgumentNullException(nameof(inviteService));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <summary>
    /// Generates a new invite link with QR code
    /// </summary>
    /// <param name="request">The invite generation request</param>
    /// <returns>Invite link, QR code, and expiration details</returns>
    [HttpPost("generate")]
    [ProducesResponseType(typeof(GenerateInviteResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GenerateInvite([FromBody] GenerateInviteRequest request)
    {
        try
        {
            // Get user ID from JWT claims
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (string.IsNullOrWhiteSpace(userId))
            {
                _logger.LogWarning("Invite generation attempted without valid user ID in token");
                return Unauthorized(new { message = "Invalid authentication token." });
            }

            // Validate expiry hours
            if (request.ExpiryHours <= 0 || request.ExpiryHours > 168) // Max 1 week
            {
                return BadRequest(new { message = "Expiry hours must be between 1 and 168 (1 week)." });
            }

            // Generate invite token
            var inviteToken = await _inviteService.GenerateInviteLinkAsync(userId, request.ExpiryHours);

            // Construct full invite link URL
            var baseUrl = $"{Request.Scheme}://{Request.Host}";
            var inviteLink = $"{baseUrl}/register?invite={inviteToken}";

            // Generate QR code
            var qrCodeDataUrl = _inviteService.GenerateInviteQrCode(inviteLink);

            // Calculate expiration time
            var expiresAt = DateTime.UtcNow.AddHours(request.ExpiryHours);

            _logger.LogInformation("Invite generated by user {UserId}, expires at {ExpiresAt}", userId, expiresAt);

            return Ok(new GenerateInviteResponse
            {
                InviteCode = inviteToken,
                InviteLink = inviteLink,
                QrCodeDataUrl = $"data:image/png;base64,{qrCodeDataUrl}",
                ExpiresAt = expiresAt
            });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating invite");
            return StatusCode(StatusCodes.Status500InternalServerError, "An error occurred while generating the invite.");
        }
    }
}
